### ISSUE TITLE
[Bug] Controller not opening in workflows with previous controller version

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#172]
Controller is not opening anymore, both clicking on sidebar button or using shortcut.

Console error:

panel_entry.js:63 Uncaught TypeError: Cannot set properties of undefined (setting 'innerText')
    at new Entry (panel_entry.js:63:48)
    at nodeblock.js:158:23
    at Array.forEach (<anonymous>)
    at NodeBlock.build_nodeblock (nodeblock.js:155:28)
    at new NodeBlock (nodeblock.js:25:14)
    at ControllerPanel.maybe_create_node_block_for_node (controller_panel.js:150:32)
    at ControllerPanel.consider_adding_node (controller_panel.js:180:22)
    at controller_panel.js:308:51
    at Array.forEach (<anonymous>)
    at ControllerPanel._build_controllerPanel (controller_panel.js:308:29)

**Comment by LukeG89** [comment]
**Update:** This problem only occurs in my testing workflow. In new ones there is no problem. I guess it is a compatibility issue with previous controllers.

**Comment by chrisgoringe** [comment]
Should be resolved now. Please check!

**Comment by LukeG89** [comment]
Yes, it's fixed!
